- hosts: tag_Name_web_server_*
  become: yes
  tasks:
  - name: Ping Machines
    ansible.builtin.ping:    
  
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Create index.html
    ansible.builtin.command: touch /var/www/html/index.html  
  
  - name: Copy New index.html to /var/www/html/
    ansible.builtin.copy:
      src: tmp/index.html
      dest: /var/www/html/index.html

  
- hosts: tag_Name_web_server_2
  become: yes
  tasks:
  - name: Write Unique Content Inside Web Server 2
    ansible.builtin.lineinfile:
      path: /var/www/html/index.html
      regexp: '<p>my name is machine 1, watch out for machine 2</p>'
      line: <p>my name is machine 2, watch out for machine 3</p>


      













  #- name: Install packages
   # yum:
    #  name: "{{ packages }}"
    #vars:
    #  packages:
     #   - git
      #  - pip
       # - docker

#  - name: Install boto package
 #   pip:
  #    name: "{{ packages2 }}"
   # vars:
    #  packages:
     #   - boto
      
 # - name: Start service docker, if not started
  #  ansible.builtin.service:
   #   name: docker
    #  state: started

  #- name: clone a dockerfile repo
  #  ansible.builtin.git:
   #   repo: https://github.com/shegoj/2021-devopstrainingminiproject
    #  dest: /tmp/
  
  

  #tag_Name_web_server_1
  #tag_Name_web_server_2
  #tag_Name_app_tomcat_server
  #ec2_private_ip_address