- hosts: tag_Name_web_server_*
  become: yes
  tasks:
  - name: Ping Machines
    ansible.builtin.ping:    
  
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Create index.html
    ansible.builtin.command: touch /var/www/html/index.html  
  
  - name: Insert/Update HTML surrounded by custom markers after <body> line
    blockinfile:
      path: /var/www/html/index.html
      block: 
        <!DOCTYPE html>
        <html>
        <head>
        <title>Basic Web Page</title>
        </head>
        <body>
        <p> HELLO WORLD THIS OS SERVER 1 (ONE) </p>
        </body>
        </html>
        
  
- hosts: tag_Name_web_server_2
  become: yes
  tasks:
  
  - name: Insert/Update HTML surrounded by custom markers after <body> line
    blockinfile:
      path: /var/www/html/index.html
      block: 
        <!DOCTYPE html>
        <html>
        <head>
        <title>Basic Web Page</title>
        </head>
        <body>
        <p> HELLO WORLD THIS IS SERVER 2 (TWO) </p>
        </body>
        </html>


      













  #- name: Install packages
   # yum:
    #  name: "{{ packages }}"
    #vars:
    #  packages:
     #   - git
      #  - pip
       # - docker

#  - name: Install boto package
 #   pip:
  #    name: "{{ packages2 }}"
   # vars:
    #  packages:
     #   - boto
      
 # - name: Start service docker, if not started
  #  ansible.builtin.service:
   #   name: docker
    #  state: started

  #- name: clone a dockerfile repo
  #  ansible.builtin.git:
   #   repo: https://github.com/shegoj/2021-devopstrainingminiproject
    #  dest: /tmp/
  
  

  #tag_Name_web_server_1
  #tag_Name_web_server_2
  #tag_Name_app_tomcat_server
  #ec2_private_ip_address